import type { Metadata } from "next";
import Link from "next/link";
import Script from "next/script";

export const metadata: Metadata = {
  title: "FAQ | MeetMind AI",
  description: "Frequently asked questions about MeetMind AI. Learn how our AI meeting assistant transcribes, summarizes, and extracts action items from your calls.",
  openGraph: {
    title: "FAQ | MeetMind AI",
    description: "Frequently asked questions about MeetMind AI.",
    url: "https://meetmindai.co.in/faq",
    siteName: "MeetMind AI",
    locale: "en_US",
    type: "website",
  },
  alternates: {
    canonical: "https://meetmindai.co.in/faq",
  },
};

const faqs = [
  {
    question: "How accurate is the AI transcription?",
    answer: "Our transcription engine leverages state-of-the-art models (like Whisper) which boast a near 99% accuracy rate across standard English. It handles varying accents well, though heavy background noise may slightly impact results."
  },
  {
    question: "Do you use my meeting data to train your AI?",
    answer: "No. Privacy is our top priority. Your meeting data is processed solely to provide you with transcripts and summaries. We enforce zero-retention policies with our LLM partners, meaning your data is never used to train public models."
  },
  {
    question: "Which languages does MeetMind AI support?",
    answer: "Currently, MeetMind AI works best with English, but our transcription engine supports over 50 languages including Spanish, French, German, and Japanese. Summary generation is currently optimized for English output."
  },
  {
    question: "Can I use MeetMind AI with Zoom, Google Meet, and Teams?",
    answer: "Yes! MeetMind AI is designed to work seamlessly with all major video conferencing platforms. You can upload any standard audio or video file (MP3, MP4, WAV, M4A) generated by these platforms."
  },
  {
    question: "What happens if I delete a meeting?",
    answer: "When you delete a meeting from your history, it is permanently removed from our active databases and storage buckets. We do not keep hidden soft-deleted copies of your proprietary data."
  }
];

export default function FAQPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map(faq => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      }
    }))
  };

  return (
    <div className="min-h-screen bg-background">
      <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      
      {/* Breadcrumbs */}
      <div className="border-b border-white/5 bg-surface/30">
        <div className="mx-auto max-w-5xl px-6 py-4 sm:px-8 lg:px-8">
          <nav className="flex text-sm text-muted" aria-label="Breadcrumb">
            <ol className="inline-flex items-center space-x-1 md:space-x-3">
              <li className="inline-flex items-center">
                <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
              </li>
              <li>
                <div className="flex items-center">
                  <span className="mx-2 text-muted-foreground">›</span>
                  <span className="text-foreground font-medium" aria-current="page">FAQ</span>
                </div>
              </li>
            </ol>
          </nav>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-6 py-16 sm:px-8 lg:px-8">
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-muted">
            Everything you need to know about how MeetMind AI works.
          </p>
        </div>

        <div className="space-y-6 mb-20">
          {faqs.map((faq, index) => (
            <div key={index} className="rounded-2xl border border-card-border bg-surface p-6 sm:p-8">
              <h3 className="text-xl font-semibold text-foreground mb-3">{faq.question}</h3>
              <p className="text-muted leading-relaxed">{faq.answer}</p>
            </div>
          ))}
        </div>

        {/* CTA Section */}
        <div className="text-center rounded-2xl border border-card-border bg-gradient-to-br from-surface to-surface/50 p-8 sm:p-12">
          <h2 className="text-2xl font-bold text-foreground mb-4">
            Ready to save time in your meetings?
          </h2>
          <p className="text-muted mb-8 max-w-xl mx-auto">
            Stop taking manual notes and let AI handle the heavy lifting.
          </p>
          <Link
            href="/login"
            className="inline-flex items-center justify-center rounded-xl bg-gradient-to-r from-accent-purple to-accent-blue px-8 py-4 text-base font-semibold text-white shadow-sm hover:scale-[1.03] transition-all focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent-purple"
          >
            Try MeetMind AI for free
          </Link>
        </div>
      </div>
    </div>
  );
}
